-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 10:55:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio` (
  `por_id` INT(10) UNSIGNED NOT NULL,
  `por_title` VARCHAR(124) NOT NULL,
  `por_text` TEXT NOT NULL,
  `por_image` VARCHAR(255) NOT NULL,
  `por_link` VARCHAR(255) NOT NULL,
  `por_inserted` DATETIME NOT NULL,
  `por_updated` TIMESTAMP NOT NULL,
  PRIMARY KEY (`por_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
